arr=[1,2,0,1,2,1,0,1,2,1,2,0]
high=len(arr)-1
low=0
mid=0
while(mid<=high):
    if(arr[mid]==0):
        arr[low],arr[mid]=arr[mid],arr[low]
        mid+=1
        low+=1
    elif(arr[mid]==1):
        mid+=1
    else:
        arr[high],arr[mid]=arr[mid],arr[high]
        high-=1
print(arr)
